Password auth and cache (#1)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,36 +1,56 @@
 name: 'Deploy to Rezoleo via SFTP'
-description: 'Prépare un dossier et déploie son contenu sur Hippolyte via SFTP avec lftp + clé SSH'
+description: "Deploys the repo's content to Hippolyte via SFTP with lftp, ignoring the .git/ folder and respecting the .gitignore. A password XOR an SSH key needs to be provided."
 inputs:
-  sftp-key:
-    description: 'Clé privée SSH pour le serveur SFTP'
-    required: true
   sftp-user:
-    description: 'Nom d’utilisateur pour le serveur SFTP'
+    description: 'Username for the SFTP server'
     required: true
+  sftp-password:
+    description: 'Password for the SFTP server'
+    required: false
+  sftp-key:
+    description: 'SSH key for the SFTP server'
+    required: false
 
 runs:
   using: "composite"
   steps:
-    - name: Préparer le dossier clean
+    - name: Verify the inputs
       run: |
-        mkdir upload_clean
-        shopt -s dotglob
-        find . -mindepth 1 -maxdepth 1 ! -name upload_clean -exec cp -r {} upload_clean/ \;
-        rm -rf upload_clean/.git
+        A="${{ inputs.sftp-password }}"
+        B="${{ inputs.sftp-key }}"
+
+        if { [[ -n "$A" && -z "$B" ]] || [[ -z "$A" && -n "$B" ]]; }; then
+          echo "Good : A single means of authentication has been provided, as requested."
+        else
+          echo "Error : Only a single means of authentication needs to be provided (password xor key)."
+          exit 1
+        fi
       shell: bash
 
-    - name: Installer lftp
-      run: sudo apt-get update && sudo apt-get install -y lftp
+    - name: Install lftp package
+      uses: awalsh128/cache-apt-pkgs-action@v1.5.1
+      with:
+        packages: lftp
+        version: 1.0
+
+    - name: Deploy via lftp with password
+      if: ${{ inputs.sftp-password != '' }}
+      env:
+        SFTP_USER: ${{ inputs.sftp-user }}
+        SFTP_PASSWORD: ${{ inputs.sftp-password }}
+      run: |
+        lftp -p 8888 "sftp://$SFTP_USER:$SFTP_PASSWORD@sftp.rezoleo.fr" -e "set cmd:trace true; set sftp:auto-confirm yes; mirror --delete --reverse --exclude=.git --exclude-glob-from=.gitignore ./ ./writable ; quit"
       shell: bash
 
-    - name: Écrire la clé privée
+    - name: Write the private key to ../id_rsa
+      if: ${{ inputs.sftp-key != '' }}
       run: |
-        echo "${{ inputs.sftp-key }}" > id_rsa
-        chmod 600 id_rsa
+        echo "${{ inputs.sftp-key }}" > ../id_rsa 
+        chmod 600 ../id_rsa
       shell: bash
 
-    - name: Déployer via lftp
+    - name: Deploy via lftp with key
+      if: ${{ inputs.sftp-key != '' }}
       run: |
-        cd upload_clean
-        lftp -u "${{ inputs.sftp-user }}","" -e "set sftp:connect-program 'ssh -i ../id_rsa -o StrictHostKeyChecking=no -p 8888'; set ssl:verify-certificate no; mirror -R --delete --exclude-glob .git/ ./ /writable/; bye" sftp://sftp.rezoleo.fr
+        lftp -u "${{ inputs.sftp-user }}","" -e "set cmd:trace true; set sftp:connect-program 'ssh -i ../id_rsa -o StrictHostKeyChecking=no -p 8888'; set ssl:verify-certificate no; mirror --delete --reverse --exclude=.git/ --exclude-glob-from=.gitignore ./ /writable/; quit" sftp://sftp.rezoleo.fr
       shell: bash
